### ISSUE TITLE
Way to extract just one file from an archive?

### ISSUE THREAD

**Issue by TranquilMarmot** [nika-begiashvili/libarchivejs#1]
You can call `getFilesObject` and `getFilesArray` to get a list of all of the files in an archive, but it seems like the only option to extract any files is to call `extractFiles` which extracts _all_ of the files.

Would it be possible to add a way to only extract one of the files in the array?

**Comment by nika-begiashvili** [comment]
Yes! I was actually planning this, my idea is for getFilesObject and getFilesArray to return CompressedFile objects ( unless you run extractFiles() ) which would have extract() method on it, what do you think about that kind of API ?

**Comment by TranquilMarmot** [comment]
That sounds great! My use case is to basically stream in one file at a time (i.e. paging through images in a zip) so that would work awesome.

**Comment by nika-begiashvili** [comment]
do you mind trying it out before I merge it ?
https://github.com/nika-begiashvili/libarchivejs/tree/single-file-extract

**Comment by nika-begiashvili** [comment]
#4

**Comment by nika-begiashvili** [comment]
Released as v1.1.0
