### ISSUE TITLE
Can't extract gz

### ISSUE THREAD

**Issue by wyrj** [nika-begiashvili/libarchivejs#14]
Version: 1.3.0
Symptom: extract gz would get `Memory read error -30`

I found related [issue](https://github.com/libarchive/libarchive/issues/1173) and [mr](https://github.com/libarchive/libarchive/pull/958) in libarchive and fix it in v3.4.0

Do you have any plan to upgrade?

Thanks

**Comment by nika-begiashvili** [comment]
Libarchive.js is using libarchive 4, so issue is probably on libarchive.js side, I'll look into it

**Comment by nika-begiashvili** [comment]
#25

**Comment by idolpx** [comment]
Sorry I did not see this sooner.  I'm using libarchivejs in a browser app that lets you explore the contents of media files.

https://meatloaf.cc/tools/mme/

Sometimes those files are just compressed but not in an archive.
