### ISSUE TITLE
Can use by nodejs?

### ISSUE THREAD

**Issue by mondy** [nika-begiashvili/libarchivejs#16]
Hi. 

Are there any plans to make it available on nodejs?

I think so, If it wasm, porting to nodejs is easy.
But I'm not sure.

I hope it can be used by nodejs.

**Comment by nika-begiashvili** [comment]
Hi, I'm wanted this to work with nodejs from the start but unfortunately issue lies within WebWorkers not webassembly, API is too different to handle both
my plan was to use https://github.com/GoogleChromeLabs/comlink which works with worker_threads as well but unfortunately I'm not able to make it work for now
I would appreciate help

**Comment by mondy** [comment]
Thanks for reply.
I don't understand this library in detail yet.
So I couldn't help you. I'm sorry.

**Comment by wachidmudi** [comment]
Yeah, my first thought of this library is that it can be used inside nodejs only, but it really need a WebWorkers that lies within a browser. Just bear with it for now. 😂

**Comment by btzr-io** [comment]
You don't need `webworkers` on nodejs, you can use `libarchive`  directly by  creating a [`build`](https://github.com/libarchive/libarchive/wiki/BuildInstructions) or use the c++ biindings:

This repository looks unmaintained but it can help:
https://github.com/skomski/node-archive

**Comment by nika-begiashvili** [comment]
@btzr-io I agree that's probably best solution for now, but since that doesn't really produce portable package (you need to have libarchive on system) I'm still interested making libarchive.js available for nodejs

**Comment by btzr-io** [comment]
The api looks similar: https://nodejs.org/api/worker_threads.html
you could switch to `worker_threads` if is on `node`

**Comment by nika-begiashvili** [comment]
> Not sure if is possible to use / integrate this but the api looks similar: https://nodejs.org/api/worker_threads.html
> you could switch to `worker_threads` if is on `node`...
> 
> Oh , I didn't see this message:
> 
> > my plan was to use https://github.com/GoogleChromeLabs/comlink which works with worker_threads as well but unfortunately I'm not able to make it work for now
> 
> Whats the issue with comlink ?

honestly, it kinda doesn't work :D message doesn't go through unless you debug it, when you're debugging, it works as expected, need more time to investigate

**Comment by drola** [comment]
Could you upload your experiment to a separate branch here?
