### ISSUE TITLE
How to extract to local directory?

### ISSUE THREAD

**Issue by wachidmudi** [nika-begiashvili/libarchivejs#17]
Sorry for asking a newbie question again, but it's keep bugging my mind.
I can listing the file inside an archive and log to the console, but i can't see the file in my local directory, am i missing something?

This is my code
```
function finish() {
    const d = document.createElement('div');
    d.setAttribute('id', 'done');
    d.textContent = 'Done.';
    document.body.appendChild(d);
}

document.getElementById('file').addEventListener('change', async e => {
    let obj = null;

    try {
        const file = e.currentTarget.files[0];
        const archive = await Archive.open(file);
        //obj = await archive.extractFiles();
        await archive.extractFiles();
        //console.log(obj);
    } catch (err) {
        console.error(err);
    } finally {
        //window.obj = obj;
        finish();
    }
}
```

Help please, thank's.

**Comment by nika-begiashvili** [comment]
This library returns native web File objects
https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications
What you'll do with it is up to you

**Comment by wachidmudi** [comment]
Many Thanks. After couple of try then it's really working now. To save the file to local directory it's need to be downloaded first with the path depends on browser's default configuration.
