### ISSUE TITLE
Suppot unicode on file names

### ISSUE THREAD

**Issue by btzr-io** [nika-begiashvili/libarchivejs#19]
Unicode symbols / characters are not detected so they are replaced on  the path name
```
À.png --> *.png
```

See: No way to retrieve filename in UTF-8 without setting locale [#587](https://github.com/libarchive/libarchive/issues/587) 

[More Related issues](https://github.com/libarchive/libarchive/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unicode)

**Comment by nika-begiashvili** [comment]
I'll look into it

**Comment by nika-begiashvili** [comment]
added in #64
