### ISSUE TITLE
Unsorted files on rar archives

### ISSUE THREAD

**Issue by btzr-io** [nika-begiashvili/libarchivejs#22]
`getFilesArray()` is returning unsorted items for some rar archives.
Example archive: https://github.com/workhorsy/uncompress.js/blob/master/example_rar_5.rar

Any ideas why ?

**Comment by btzr-io** [comment]
Test this archives:
https://github.com/workhorsy/uncompress.js

**Comment by nika-begiashvili** [comment]
I believe libarchive is returning files "as is" written inside file, meaning order is specific to however archive was created, do you have any reason to think it might not be that case ?

**Comment by btzr-io** [comment]
Got the same result with:
https://wcchoi.github.io/libunrar-js/

**Comment by btzr-io** [comment]
Just in case someone has the same problem:

```js  
    const files = await archive.current.getFilesArray()
    // Sort files by name
    files.sort((a, b) => {
        if (a.file.name > b.file.name) return 1
        if (a.file.name < b.file.name) return -1
        return 0
     })
```
