### ISSUE TITLE
'worker-bundle' file alwsys throw error like 'Uncaught SyntaxError: Unexpected token '<''

### ISSUE THREAD

**Issue by zzy5921** [nika-begiashvili/libarchivejs#26]
like this ,
my vue project want to unzip some zipfile,
so import your 'libarchive.js' to do this,
but in the browser always thorw an error like `Uncaught SyntaxError: Unexpected token '<'`,
there is my code:
`    Archive.init('../../node_modules/libarchive.js/dist/worker-bundle.js');
      const archive = await Archive.open(zipFile);
      let obj = await archive.extractFiles();
      console.log(obj);`
`zipfile` is my zipfile and init path is true or empty always throw this error.
my English is not good, washing your reply.

**Comment by nika-begiashvili** [comment]
could you give me line number and related code where it throws error ?

**Comment by hxlyd** [comment]
https://github.com/nika-begiashvili/libarchivejs/issues/13#issuecomment-531127643
@zzy5921
