### ISSUE TITLE
How can I get unzipped file data from entry data?

### ISSUE THREAD

**Issue by gracegyu** [nika-begiashvili/libarchivejs#32]
{File} contains only file name, date, etc.

How can I get file data?

```
archive.extractFiles((entry) => { // { file: {File}, path: {String} }
        console.log(entry);
});
```

**Comment by btzr-io** [comment]
"File" is a `file` object:

> A File object is a specific kind of a Blob, and can be used in any context that a Blob can. In particular, FileReader, URL.createObjectURL(), createImageBitmap(), and XMLHttpRequest.send() accept both Blobs and Files.

See: https://developer.mozilla.org/en-US/docs/Web/API/File

You can use the FileReader API: https://developer.mozilla.org/en-US/docs/Web/API/FileReader

**Comment by gracegyu** [comment]
I can get file data using this code. Thanks.
```
archive.extractFiles((entry) => { 
        let reader = new FileReader();
        reader.readAsArrayBuffer(entry.file);

        reader.onload = function() {
            console.log('file data', reader.result);
        };
});
```
