### ISSUE TITLE
Better Bundling support

### ISSUE THREAD

**Issue by nikeee** [nika-begiashvili/libarchivejs#48]
Passing the URL to worker may not work due to bundlers mangling file names:

```js
this._worker = new Worker(options.workerUrl);
```

Maybe that could be solved by allowing passing the worker directly:
```js
this._worker = options.worker
    ? options.worker
    : new Worker(options.workerUrl);
```

**Comment by lrx1234** [comment]
![1701414427043](https://github.com/nika-begiashvili/libarchivejs/assets/64525352/3581441a-bc7f-41b1-a53e-390c8ba98437)
Do you have this problem when using Archive.init({workerUrl: 'libarchive.js/dist/worker-bundle.js'})

**Comment by nika-begiashvili** [comment]
There are bundling examples in v2.0.1
