### ISSUE TITLE
can I extract a protected zip file (with password)

### ISSUE THREAD

**Issue by landvibe** [nika-begiashvili/libarchivejs#5]
.

**Comment by nika-begiashvili** [comment]
Unfortunately not, to bring decryption functionality from libarchive requires to compile openssl to webassembly and it will increase wasm file size as well. this is certainly possible but would make sense to introduce different wasm bundles

**Comment by nika-begiashvili** [comment]
Starting from 1.3.0 you can now extract password protected archives

### Extract encrypted archive

```js
    const archive = await Archive.open(file);
    await archive.usePassword("password");
    let obj = await archive.extractFiles();
```
