### ISSUE TITLE
Please update this package. Or teach us how to do it.

### ISSUE THREAD

**Issue by redthing1** [nika-begiashvili/libarchivejs#57]
Please update this package, or give me instructions on how to update it to latest libarchive and I'll PR.

**Comment by 20hertz** [comment]
For upgrading libarchive, I guess you can checkout #52 to see how @sharkymcdongles did it.

**Comment by nika-begiashvili** [comment]
New version out!

**Comment by redthing1** [comment]
Thank you very much!
