### ISSUE TITLE
When libarchivejs parses Chinese names, it will be replaced by *

### ISSUE THREAD

**Issue by onlyalive** [nika-begiashvili/libarchivejs#58]
When libarchivejs parses Chinese names, it will be replaced by *
![bug](https://github.com/nika-begiashvili/libarchivejs/assets/65668795/feda5b6d-5d2a-4872-9efc-f8f6252f5969)

**Comment by onlyalive** [comment]
可以去 npm 官网搜索 vue-files-viewer 插件，使用 libarchivejs 二次开发的，修复不能显示中文名的问题

**Comment by Luoxue-xu** [comment]
> 可以去 npm 官网搜索 vue-files-viewer 插件，使用 libarchivejs 二次开发的，修复不能显示中文名的问题

你好，可以分享一下你是怎么解决的吗？我也遇到了这个问题。

**Comment by Luoxue-xu** [comment]
> 可以去 npm 官网搜索 vue-files-viewer 插件，使用 libarchivejs 二次开发的，修复不能显示中文名的问题

我测试发现，你并没有解决zip和7z格式的中文解析异常问题。

**Comment by onlyalive** [comment]
> > 可以去 npm 官网搜索 vue-files-viewer 插件，使用 libarchivejs 二次开发的，修复不能显示中文名的问题
> 
> 我测试发现，你并没有解决zip和7z格式的中文解析异常问题。

是不是没注意这个
![image](https://github.com/nika-begiashvili/libarchivejs/assets/65668795/53c8f368-a642-4d8f-b220-80fb6e9b9562)

**Comment by Jack402** [comment]
> > > 可以去 npm 官网搜索 vue-files-viewer 插件，使用 libarchivejs 二次开发的，修复不能显示中文名的问题
> > 
> > 
> > 我测试发现，你并没有解决zip和7z格式的中文解析异常问题。
> 
> 是不是没注意这个 ![image](https://private-user-images.githubusercontent.com/65668795/282974019-53c8f368-a642-4d8f-b220-80fb6e9b9562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTg3NDUsIm5iZiI6MTcwMjQ1ODQ0NSwicGF0aCI6Ii82NTY2ODc5NS8yODI5NzQwMTktNTNjOGYzNjgtYTY0Mi00ZDhmLWIyMjAtODBmYjZlOWI5NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjI5ZjMwMDQ2MjgwMDQzY2QyMTBiNGFkZWE5NWY5ZGY5MjE0ZTEzMzEwZGMxMjIxNzFjZmY5ZjllZDA1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVscYh3KVof2I1DEA3P1xjlG2Mau9OIMMu7PKMaEsac)

复制过去了，还是不行

**Comment by nika-begiashvili** [comment]
This is fixed in v2.0.0 #64
