### ISSUE TITLE
When using libarchivejs to decompress certain ZIP formats, if the compressed package contains files with Chinese names, the decompressed file names will return empty.

### ISSUE THREAD

**Issue by PCAaron** [nika-begiashvili/libarchivejs#59]
When using libarchivejs to decompress certain ZIP formats, if the compressed package contains files with Chinese names, the decompressed file names will return empty.
![image](https://github.com/nika-begiashvili/libarchivejs/assets/25318681/e2bc5e47-a432-4d9f-b8de-1dd41ac3f8a8)

**Comment by Klivitam** [comment]
what to finish？i meet too

**Comment by nika-begiashvili** [comment]
This is fixed in v2.0.0 #64
