### ISSUE TITLE
How to know a archive file is encrypted or not?

### ISSUE THREAD

**Issue by wyrj** [nika-begiashvili/libarchivejs#6]
It seems encrypted archive file can not be extracted.

How to know a archive file is encrypted (or could be extracted) before I call the extract function?

**Comment by nika-begiashvili** [comment]
there's archive_read_has_encrypted_entries function which I haven't ported yet but it should be fairly easy, I'll put it as my next task or you could PR if you want to

**Comment by nika-begiashvili** [comment]
now you can check if archive contains encrypted data
https://github.com/nika-begiashvili/libarchivejs#check-for-encrypted-data
