### ISSUE TITLE
code error when I using 'Archive.init({           workerUrl: 'libarchivejs/dist/worker-bundle.js'       })  '

### ISSUE THREAD

**Issue by lrx1234** [nika-begiashvili/libarchivejs#60]
![image](https://github.com/nika-begiashvili/libarchivejs/assets/64525352/bf1d0333-cd67-42bb-9ce7-ca7b1901e9ba)
![image](https://github.com/nika-begiashvili/libarchivejs/assets/64525352/3ccfc567-681f-4fc6-91d4-2378e9ce2fc2)

**Comment by nika-begiashvili** [comment]
Try latest version, it also comes with bundling examples
