### ISSUE TITLE
working example for creating and writing archive files in node and browser 

### ISSUE THREAD

**Issue by ganeshkbhat** [nika-begiashvili/libarchivejs#63]
Any working example present for creating and writing archive files in node and browser? https://github.com/nika-begiashvili/libarchivejs/issues/54

**Comment by nika-begiashvili** [comment]
Unfortunately this version doesn't support node or creating archives but I'm currently working on version 2 https://github.com/nika-begiashvili/libarchivejs/tree/v2 which will support both

**Comment by nika-begiashvili** [comment]
It's published! please let me know if you encounter any bugs

**Comment by sp90** [comment]
@nika-begiashvili want a separate ticket for @types/libarchive.js v2?

**Comment by sp90** [comment]
Think i resolved the typing by using `libarchive.js/src/libarchive` over `'libarchive.js` as the import source

**Comment by nika-begiashvili** [comment]
There are typescript built files in dist, I'm probably missing a way to expose it, I'll look into it

**Comment by nika-begiashvili** [comment]
Added "types" field to package.json, can you please check if it works in latest version ? @sp90

**Comment by sp90** [comment]
Now works as expected amazing 👍
