### ISSUE TITLE
Promise.withResolvers

### ISSUE THREAD

**Issue by sp90** [nika-begiashvili/libarchivejs#65]
When trying to create an archive in the browser `chrome v120` i get the 

```
ERROR TypeError: Promise.withResolvers is not a function
```

this is probably due to it not being supported yet in most browsers suggesting an alternative implementation like

```
let resolve, reject;

const promise = new Promise((res, rej) => {
  resolve = res;
  reject = rej;
});
```

I know it doesn't look as nice in the code but its gonna have a much better browser support

**Comment by nika-begiashvili** [comment]
Use this polyfill for now, I'll include it in next version 

'''js
// Polyfill for Promise.withResolvers on nodejs
(Promise as any).withResolvers ||
  ((Promise as any).withResolvers = function withResolvers() {
    var a,
      b,
      c = new this(function (resolve: Function, reject: Function) {
        a = resolve;
        b = reject;
      });
    return { resolve: a, reject: b, promise: c };
  });
'''
