### ISSUE TITLE
Error: Buffer exhausted

### ISSUE THREAD

**Issue by sp90** [nika-begiashvili/libarchivejs#66]
I'm working with `libarchive.js` in the browser and it seems that I load the worker correctly when i try to create a ZIP using this code bit:

<img width="731" alt="Screenshot 2024-01-22 at 13 22 25" src="https://github.com/nika-begiashvili/libarchivejs/assets/3041602/85bffb47-ccbc-4b99-84d9-702c37838d22">

I get `Error: Buffer exhausted`

<img width="1126" alt="Screenshot 2024-01-22 at 13 23 54" src="https://github.com/nika-begiashvili/libarchivejs/assets/3041602/fc81ae0d-cc14-4f7a-a128-a1ab5282d297">

And in the worker reference, I get this code:

<img width="455" alt="Screenshot 2024-01-22 at 13 23 59" src="https://github.com/nika-begiashvili/libarchivejs/assets/3041602/92adcf33-96a4-434d-a6dd-131fabeea5cb">

I wanna disclaim I'm a bit in doubt about the compression and format what works together and how do i get a ZIP file

**Comment by sp90** [comment]
If I then use the example config:

<img width="455" alt="Screenshot 2024-01-22 at 13 31 57" src="https://github.com/nika-begiashvili/libarchivejs/assets/3041602/c644259d-d694-4ce5-9107-706a5a25d845">


I get `89 bytes` based on compressing a `9756 bytes` file and when I try to "unzip" I get this error I'm on mac 

<img width="374" alt="Screenshot 2024-01-22 at 13 33 39" src="https://github.com/nika-begiashvili/libarchivejs/assets/3041602/f278b46a-4ddd-4d67-9928-c2caf0969ef2">

**Comment by nika-begiashvili** [comment]
can you share log for `fileMap` ? also is passphrase set ?

**Comment by sp90** [comment]
Same as the screenshot at the top 🙏🏼

**Comment by sp90** [comment]
Its a single file in the array and the passphrase is 'null'

**Comment by nika-begiashvili** [comment]
Yes, please share the file and a code so I could replicate

**Comment by sp90** [comment]
I get a different error than the buffer exhausted in this example but maybe solving this might solve the other problem as well

```
https://github.com/sp90/test-archive/tree/main
```

**Comment by nika-begiashvili** [comment]
I think there's exactly the same code as a test which is passing https://github.com/nika-begiashvili/libarchivejs/blob/master/test/files/write-archive.html so I can't see how I can reproduce this  
does error occur with any file ?

**Comment by sp90** [comment]
Well, this example only extracts a zip I'm trying to create one :) and i get the error with any file i try to upload small or big

**Comment by nika-begiashvili** [comment]
Can you try this file see if it works ? https://github.com/nika-begiashvili/libarchivejs/blob/master/test/files/write-archive.html
  
it also has download function for convenience

**Comment by sp90** [comment]
I get this console error:

<img width="1151" alt="Screenshot 2024-01-25 at 15 51 29" src="https://github.com/nika-begiashvili/libarchivejs/assets/3041602/76ea902f-a794-44ce-9975-75f8b8604f72">

Btw I'm greatly appreciative of your help!!

**Comment by nika-begiashvili** [comment]
I was able to reproduce it, I'll try to investigate

**Comment by sp90** [comment]
Much appreciated

**Comment by nika-begiashvili** [comment]
Fixed in 0989c1a6db20d030d793b1763e20d880068091bd

**Comment by sp90** [comment]
@nika-begiashvili it works flawless now thanks for the support on the topic

**Comment by frodo821** [comment]
Using version 2.0.2 of libarchive.js, I'm still suffering from this error.

It's the same as the above setup (archiving with USTAR, gzip-compressed, without setting a passphrase, compressing a single file) but seemingly reproduced with some specific files (it works well with no errors for almost all files else regardless of the number of files archived at once).

![00001-44964795](https://github.com/user-attachments/assets/842af94f-2437-45df-8693-3b5e81cd6223)

This attached image is one example of files that cannot be archived with libarchive.js.

**Comment by frodo821** [comment]
~~I may have just uncovered what's wrong. The tar format demands 512 bytes for each file entry's header field, but it serves only 128 bytes each. However, if this is the right cause, I wonder why it works perfectly with almost all files.~~ No, it's not the true cause. Still in trouble.
