### ISSUE TITLE
Unsupported block header size (was 5, max is 2)

### ISSUE THREAD

**Issue by ducladev** [nika-begiashvili/libarchivejs#68]
Hello,

I come from Vietnam, thank you for developing and sharing such a wonderful library. However, I encountered an issue with a RAR file with the password: "Unsupported block header size (was 5, max is 2)".

![Screenshot 2024-03-22 090053](https://github.com/nika-begiashvili/libarchivejs/assets/148784065/69da732f-577a-4585-88f2-4e240db220c2)

I have used `wait archive.hasEncryptedData();`  to check, but the result returned `null` instead of `true`.

I am using version `v1.3.0`  in an Angular application. I would greatly appreciate your assistance!

Best regards,
Anh Duc Le

**Comment by nika-begiashvili** [comment]
Please try latest version v2.0.2 and reopen an issue if problem persists

**Comment by ducladev** [comment]
The latest version is not compatible with my current Angular version. I installed v2.0.2 and still have the same error.
